repos:

- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    # args: [--quiet]
    language: system
    types: [python]
    files:
      src/euchre/
      tests/

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: flake8
    entry: flake8
